"""Device profiles for ZHA Advanced Toolkit."""

from __future__ import annotations

from .const import (
    CATEGORY_DIMMING,
    CATEGORY_LED,
    CATEGORY_MMWAVE,
    CATEGORY_PROTECTION,
    CATEGORY_REPORTING,
    CATEGORY_SWITCH,
    INOVELLI_MANUFACTURER_CODE,
)
from .models import (
    CommandEntityDescription,
    NumberEntityDescription,
    Profile,
    SelectEntityDescription,
    SwitchEntityDescription,
    option,
)

EP1 = 1
INOVELLI_CONFIG_CLUSTER = 0xFC31
INOVELLI_MMWAVE_CLUSTER = 0xFC32


VZM32_SN = Profile(
    name="Inovelli VZM32-SN",
    manufacturer="Inovelli",
    model="VZM32-SN",
    settings=(
        SelectEntityDescription(
            key="switch_mode",
            name="Switch mode",
            category=CATEGORY_SWITCH,
            endpoint_id=EP1,
            cluster_id=INOVELLI_CONFIG_CLUSTER,
            attribute_id=0x0102,
            attribute_name="output_mode",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            options=(
                option(0, "Dimmer"),
                option(1, "On / Off"),
            ),
        ),
        SelectEntityDescription(
            key="switch_type",
            name="Wiring type",
            category=CATEGORY_SWITCH,
            endpoint_id=EP1,
            cluster_id=INOVELLI_CONFIG_CLUSTER,
            attribute_id=0x0016,
            attribute_name="switch_type",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            options=(
                option(0, "Single pole"),
                option(1, "Multi-way mode 1 / aux or firmware default"),
                option(2, "Multi-way mode 2 / dumb or alternate aux"),
                option(3, "Multi-way full sine / firmware-specific"),
            ),
        ),
        SwitchEntityDescription(
            key="smart_bulb_mode",
            name="Smart bulb mode",
            category=CATEGORY_SWITCH,
            endpoint_id=EP1,
            cluster_id=INOVELLI_CONFIG_CLUSTER,
            attribute_id=0x0034,
            attribute_name="smart_bulb_mode",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
        ),
        SwitchEntityDescription(
            key="aux_switch_unique_scenes",
            name="Aux switch unique scenes",
            category=CATEGORY_SWITCH,
            endpoint_id=EP1,
            cluster_id=INOVELLI_CONFIG_CLUSTER,
            attribute_id=0x007B,
            attribute_name="aux_switch_scenes",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
        ),
        SwitchEntityDescription(
            key="local_protection",
            name="Local protection",
            category=CATEGORY_PROTECTION,
            endpoint_id=EP1,
            cluster_id=INOVELLI_CONFIG_CLUSTER,
            attribute_id=0x0100,
            attribute_name="local_protection",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
        ),
        SwitchEntityDescription(
            key="remote_protection",
            name="Remote protection",
            category=CATEGORY_PROTECTION,
            endpoint_id=EP1,
            cluster_id=INOVELLI_CONFIG_CLUSTER,
            attribute_id=0x0101,
            attribute_name="remote_protection",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
        ),
        SwitchEntityDescription(
            key="invert_switch",
            name="Invert switch",
            category=CATEGORY_SWITCH,
            endpoint_id=EP1,
            cluster_id=INOVELLI_CONFIG_CLUSTER,
            attribute_id=0x000B,
            attribute_name="invert_switch",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
        ),
        NumberEntityDescription(
            key="minimum_level",
            name="Minimum dim level",
            category=CATEGORY_DIMMING,
            endpoint_id=EP1,
            cluster_id=INOVELLI_CONFIG_CLUSTER,
            attribute_id=0x0009,
            attribute_name="minimum_level",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            native_min_value=1,
            native_max_value=254,
        ),
        NumberEntityDescription(
            key="maximum_level",
            name="Maximum dim level",
            category=CATEGORY_DIMMING,
            endpoint_id=EP1,
            cluster_id=INOVELLI_CONFIG_CLUSTER,
            attribute_id=0x000A,
            attribute_name="maximum_level",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            native_min_value=2,
            native_max_value=255,
        ),
        NumberEntityDescription(
            key="auto_off_timer",
            name="Auto-off timer",
            category=CATEGORY_SWITCH,
            endpoint_id=EP1,
            cluster_id=INOVELLI_CONFIG_CLUSTER,
            attribute_id=0x000C,
            attribute_name="auto_off_timer",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            native_min_value=0,
            native_max_value=32767,
            native_unit_of_measurement="s",
        ),
        NumberEntityDescription(
            key="led_color_when_on",
            name="LED color when on",
            category=CATEGORY_LED,
            endpoint_id=EP1,
            cluster_id=INOVELLI_CONFIG_CLUSTER,
            attribute_id=0x005F,
            attribute_name="led_color_when_on",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            native_min_value=0,
            native_max_value=255,
        ),
        NumberEntityDescription(
            key="led_intensity_when_on",
            name="LED intensity when on",
            category=CATEGORY_LED,
            endpoint_id=EP1,
            cluster_id=INOVELLI_CONFIG_CLUSTER,
            attribute_id=0x0061,
            attribute_name="led_intensity_when_on",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            native_min_value=0,
            native_max_value=100,
        ),
        NumberEntityDescription(
            key="led_color_when_off",
            name="LED color when off",
            category=CATEGORY_LED,
            endpoint_id=EP1,
            cluster_id=INOVELLI_CONFIG_CLUSTER,
            attribute_id=0x0060,
            attribute_name="led_color_when_off",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            native_min_value=0,
            native_max_value=255,
        ),
        NumberEntityDescription(
            key="led_intensity_when_off",
            name="LED intensity when off",
            category=CATEGORY_LED,
            endpoint_id=EP1,
            cluster_id=INOVELLI_CONFIG_CLUSTER,
            attribute_id=0x0062,
            attribute_name="led_intensity_when_off",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            native_min_value=0,
            native_max_value=100,
        ),
        SelectEntityDescription(
            key="light_on_presence_behavior",
            name="Light-on presence behavior",
            category=CATEGORY_MMWAVE,
            endpoint_id=EP1,
            cluster_id=INOVELLI_CONFIG_CLUSTER,
            attribute_id=0x006E,
            attribute_name="light_on_presence_behavior",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            options=(
                option(0, "Disabled"),
                option(1, "Auto on/off when occupied"),
                option(2, "Auto off when vacant"),
                option(3, "Auto on when occupied"),
                option(4, "Auto on/off when vacant"),
                option(5, "Auto on when vacant"),
                option(6, "Auto off when occupied"),
            ),
        ),
        SelectEntityDescription(
            key="mmwave_room_size_preset",
            name="mmWave room size",
            category=CATEGORY_MMWAVE,
            endpoint_id=EP1,
            cluster_id=INOVELLI_CONFIG_CLUSTER,
            attribute_id=0x0075,
            attribute_name="mmwave_room_size_preset",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            options=(
                option(0, "Custom"),
                option(1, "X-Small"),
                option(2, "Small"),
                option(3, "Medium"),
                option(4, "Large"),
                option(5, "X-Large"),
            ),
        ),
        NumberEntityDescription(
            key="mmwave_sensitivity",
            name="mmWave sensitivity",
            category=CATEGORY_MMWAVE,
            endpoint_id=EP1,
            cluster_id=INOVELLI_MMWAVE_CLUSTER,
            attribute_id=0x0070,
            attribute_name="mmwave_detect_sensitivity",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            native_min_value=0,
            native_max_value=2,
        ),
        NumberEntityDescription(
            key="mmwave_detection_timeout",
            name="mmWave detection timeout",
            category=CATEGORY_MMWAVE,
            endpoint_id=EP1,
            cluster_id=INOVELLI_MMWAVE_CLUSTER,
            attribute_id=0x0072,
            attribute_name="mmwave_hold_time",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            native_min_value=0,
            native_max_value=4294967295,
            native_unit_of_measurement="s",
        ),
        NumberEntityDescription(
            key="mmwave_stay_life",
            name="mmWave stay life",
            category=CATEGORY_MMWAVE,
            endpoint_id=EP1,
            cluster_id=INOVELLI_MMWAVE_CLUSTER,
            attribute_id=0x006C,
            attribute_name="mmwave_stay_life",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            native_min_value=0,
            native_max_value=3600,
            native_unit_of_measurement="s",
        ),
        SwitchEntityDescription(
            key="mmwave_target_info_report",
            name="mmWave target info report",
            category=CATEGORY_MMWAVE,
            endpoint_id=EP1,
            cluster_id=INOVELLI_MMWAVE_CLUSTER,
            attribute_id=0x006B,
            attribute_name="mmwave_target_info_report",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
        ),
        NumberEntityDescription(
            key="active_power_reports",
            name="Active power report threshold",
            category=CATEGORY_REPORTING,
            endpoint_id=EP1,
            cluster_id=INOVELLI_CONFIG_CLUSTER,
            attribute_id=0x0012,
            attribute_name="active_power_reports",
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            native_min_value=0,
            native_max_value=32767,
        ),
    ),
    commands=(
        CommandEntityDescription(
            key="reset_energy_meter",
            name="Reset energy meter",
            category=CATEGORY_REPORTING,
            endpoint_id=EP1,
            cluster_id=INOVELLI_CONFIG_CLUSTER,
            command_id=0x02,
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            params={},
        ),
        CommandEntityDescription(
            key="mmwave_reset_module",
            name="Reset mmWave module",
            category=CATEGORY_MMWAVE,
            endpoint_id=EP1,
            cluster_id=INOVELLI_MMWAVE_CLUSTER,
            command_id=0x00,
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            params={"control_id": 0},
        ),
        CommandEntityDescription(
            key="mmwave_generate_interference_area",
            name="Generate mmWave interference area",
            category=CATEGORY_MMWAVE,
            endpoint_id=EP1,
            cluster_id=INOVELLI_MMWAVE_CLUSTER,
            command_id=0x00,
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            params={"control_id": 1},
        ),
        CommandEntityDescription(
            key="mmwave_obtain_areas",
            name="Obtain mmWave areas",
            category=CATEGORY_MMWAVE,
            endpoint_id=EP1,
            cluster_id=INOVELLI_MMWAVE_CLUSTER,
            command_id=0x00,
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            params={"control_id": 2},
        ),
        CommandEntityDescription(
            key="mmwave_clear_interference_area",
            name="Clear mmWave interference area",
            category=CATEGORY_MMWAVE,
            endpoint_id=EP1,
            cluster_id=INOVELLI_MMWAVE_CLUSTER,
            command_id=0x00,
            manufacturer=INOVELLI_MANUFACTURER_CODE,
            params={"control_id": 3},
        ),
    ),
)

PROFILES = (VZM32_SN,)


def get_matching_profile(manufacturer: str | None, model: str | None) -> Profile | None:
    """Return a matching device profile."""
    for profile in PROFILES:
        if profile.matches(manufacturer, model):
            return profile
    return None
